### ISSUE TITLE
Diamond Fishing Rod not working correctly

### ISSUE THREAD

**Issue by Kindredd** [TheAwesomeGem/fishing-made-better#13]
So, recently i've been playing RlCraft and i wanted to go fishing with a new diamond rod modified with the fast rell, obsidian bobber and the shiny hook.
When i try to fish with that fishing rod it keeps sinking under water, so the question is
Is there any chance that a new mod update of RlCraft is having issue with fishing-made-better or it's a new mechanic that i don't know?
Hope you find this post useful.
Take care!

**Comment by fonnymunkey** [comment]
Obsidian bobber is for lava, not water. If you want to fish in water, use a different bobber.
