### ISSUE TITLE
Disable minigame?

### ISSUE THREAD

**Issue by Albeion** [TheAwesomeGem/fishing-made-better#5]
Not an issue, but I was wondering if it was possible to disable the fishing minigame and just get the fish like in normal minecraft?

**Comment by fonnymunkey** [comment]
Not currently, this may eventually be added as a config option, however as it nullifies half the point of the mod its not a super high priority.

**Comment by fonnymunkey** [comment]
Server-side option to skip the minigame added in 2.2.1, will be available when approved on Curseforge.
