### ISSUE TITLE
Inter-mod crafting recipes with knives do not work

### ISSUE THREAD

**Issue by Pingu-Pox** [TheAwesomeGem/fishing-made-better#6]
Advanced Fishing 1.12.2-1.3.3 (knife recipes are displayed in the JEI, but do not work)
Aquaculture 1.12.2-1.6.8 (knife recipes are displayed in the JEI, but do not work)
Fishing Made Better 1.12.2-2.2.4
Forge 1.12.2 - 14.23.5.2860

![image](https://user-images.githubusercontent.com/21115660/158697967-cf8a04e7-aa7b-4a5d-8148-634b4f5934da.png)
![image](https://user-images.githubusercontent.com/21115660/158698020-aba085ff-eabb-440e-9490-d060228fa12c.png)

```
# Replace/remove/override/add AdvancedFishing recipes to work better with this mod? (Does nothing if AdvancedFishing is not installed)
B:"AdvancedFishing Recipe Override"=true
# Replace/remove/override/add Aquaculture recipes to work better with this mod? (Does nothing if Aquaculture is not installed)
B:"Aquaculture Recipe Override"=true
```

I've tried in my full modpack, as well as a freshly-made instance with just the 3 mods, I can't craft fish fillets/drops from fish using knives. Would like to avoid making recipes in CraftTweaker2 for all of them if I can help it.

**Comment by fonnymunkey** [comment]
Did you pull the fish from creative/JEI/etc, or actually catch them with FishingMadeBetter.
The filleting/scaling only works with legitimately caught fish. (Not all fish have scaling recipes as well)

**Comment by Pingu-Pox** [comment]
Ah! That was the trick. I will remove the vanilla and aquaculture fishing rods from the game (or at least try to with crafttweaker , loot tables....)
