### ISSUE TITLE
[Crash Report] Completing fishing minigame causes crash with level up reloaded mod installed 

### ISSUE THREAD

**Issue by UberbeastX** [TheAwesomeGem/fishing-made-better#8]
When I complete the fishing minigame with level up reloaded installed I get a crash here is the report.
[crash-2022-07-14_00.43.34-server.txt](https://github.com/TheAwesomeGem/fishing-made-better/files/9108602/crash-2022-07-14_00.43.34-server.txt)

**Comment by fonnymunkey** [comment]
If using newer versions of levelupreloaded set levelUpPatch in the config to false

**Comment by UberbeastX** [comment]
oh ok thanks

**Comment by UberbeastX** [comment]
mb I was on the wrong page and didn't realize
