### ISSUE TITLE
Crash with Entity Purger

### ISSUE THREAD

**Issue by Cephelo** [TheAwesomeGem/fishing-made-better#9]
[crash-2022-09-28_09.57.29-server.txt](https://github.com/Wicked7000/EntityPurger/files/9666329/crash-2022-09-28_09.57.29-server.txt)
When a fishing rod from Fishing Made Better is cast into a body of water with fish in it (ex: rivers or oceans, not small lakes), and Entity Purger is installed, the game crashes.  It appears to have something to do with Entity matching?  [Here's the repo for Entity purger.](https://github.com/Wicked7000/EntityPurger/blob/b0350a2e0250dfd1aeb8fae000927c93fc772ae9/src/main/java/com/wicked/entitypurger/EntityPurgeRunner.java#L142)
Fishing Made Better v2.2.4 
Entity Purger v1.2.3
Forge 14.23.5.2860
https://www.curseforge.com/minecraft/mc-mods/entity-purger

I originally posted this issue at Wicked7000/EntityPurger#1, but the author seems to be entirely inactive.

**Comment by fonnymunkey** [comment]
What config are you using with it? I've never heard of this mod before and am unsure of why it is crashing based on the linked code, outside of it reading the config improperly.

**Comment by Cephelo** [comment]
Sorry for the delayed reply, but the developer of Entity Purger has fixed this bug as of their latest update, v1.2.4.  Apparently the crash was caused by entities with an empty ID.  Perhaps this should be remedied in FMB as well, to avoid crashes from other mods?  I'll leave that up to you - if not, this issue can be closed.

**Comment by Cephelo** [comment]
Since there's been no discussion here for some time, I'll close this issue, as it was fixed on EntityPurger's side.
